### ISSUE TITLE
Pre-Round 3 Punch List

### ISSUE THREAD

**Issue by coreymjames** [Network-Goods/impact-evaluator-tool#122]
- [x] Update Round Details page
     - [x] update voting window dates (see comments)
     - [x] Change 'Round Description' to 'Round Overview'
     - [x] Update voting window language that is hardcoded into the page above the start and end dates (see comments below)

- [x] Submission form updates
     - [x] Add updated Submission Form Description (available in comment below)
     - [x] Make sample text more accurate within the form  (in comment below)
     - [x] The blue text at the top of the submission form should say ‘Submission Form’ instead of 'Round Description'
- [ ] Updating copy outside of tool
     - [x] Notion page
     - [ ] Slacks
     - [ ] Email past participants to join new round
     - [ ] Email hackathon participants to join round

**Comment by coreymjames** [comment]
Round Details:

Voting starts **Wednesday, Feb. 22 at 00:01 UTC-5** and ends **Thursday, Feb. 23 at 23:59 UTC-5**

**Comment by coreymjames** [comment]
Project Submissions are due **Monday, Feb. 20 at 23:59 UTC-5**

**Comment by coreymjames** [comment]
**Sample text**


Project Description
"My project is..."

Progress summary
"In the past 1 month, my project has..."

FVM Tech Specs
"My project is using FVM's functionality to..."

**Comment by jmoggr** [comment]
The above request is better served as it's own issue. I've done that here:

https://github.com/Network-Goods/impact-evaluator-tool/issues/128
