### ISSUE TITLE
[Design+Flow] ROUND STAGING

### ISSUE THREAD

**Issue by coreymjames** [Network-Goods/impact-evaluator-tool#47]
**Editability**
- Add Evaluator
- Add Project
- Edit Evaluator (Change credits #, undo vote submission)
- Edit Project details
- Remove an evaluator

**Additional features:**
- Order projects alphabetically or randomly

Wireframe:
https://www.figma.com/file/nWAQ0kksqyK40TSXGjWa1j/%5Bv3%5D-Impact-Evaluator-Tool?node-id=199%3A5983&t=ttvOFFfdgIDE3Uqt-1

**Comment by coreymjames** [comment]
@jmoggr re: the ordering of projects for an IE round:

Would love the ability to order in one of three ways:
1. Alphabetically
2. Randomly
    - order is randomized _and different_ for each user
    - order is randomized and the same for all users
3. Order of submission

What is the technical difficulty of this feature set?

Would it be radically reduced if it was only two options:
- Alphabetical
- Random and identical for all users

**Comment by jmoggr** [comment]
None of those orderings is hard to do (although we are currently not tracking when a submission is added, which we should probably do).

I would prefer to implement only one, as that's less work. I think random is the only reasonable way.
